#!/bin/bash

ARCHIVEGZ="synthesis-artefact.tar.gz"
ARCHIVE="synthesis-artefact.tar"

INSTALL=TRUE

POSITIONAL_ARGS=()

while [[ $# -gt 0 ]]; do
  case $1 in
    -h|--help)
      EXTENSION="$2"
        echo "-h, --help                                        Print usage"
        echo "-u, --uninstall                                   Remove the docker/podman container"
        exit 0
        ;;
    -i|--install)
      INSTALL=TRUE
      shift # past argument
      ;;
    -u|--uninstall)
      UNINSTALL=TRUE 
      INSTALL=FALSE
      shift # past argument
      ;;
    -*|--*)
      echo "Unknown option $1"
      exit 1
      ;;
    *)
      POSITIONAL_ARGS+=("$1") # save positional arg
      shift # past argument
      ;;
  esac
done


set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters

# DATE=$(date -d "today" +"%Y-%m-%d-%H-%M")

if [ "$INSTALL" == "TRUE" ];
then 
  echo "Installing..."
  # Extract archive to .tar 
  echo "Extracting archive $ARCHIVEGZ... "
  tar -xf $ARCHIVEGZ 
  if [ $? -eq 0 ]
  then
    # Load the container image
    echo "Loading container image from archive into Docker..."
    IMAGE=$(docker load < $ARCHIVE | tail -c +14)
    if [ $? -eq 0 ]
    then
      touch .imageID
      echo $IMAGE > .imageID
      echo "Done!"
      echo "You can now run the container image using:"
      echo "./run -r [OPTIONS]"
      echo "See README for more info on running the container" 
      echo "Run ./install -u to remove the image when finished." 
    else   
      echo "Couldn't load the container image into Docker!"
    fi
  else 
    echo "Couldn't find the archive!"
  fi
elif [ "$UNINSTALL" == "TRUE" ];
then 
  IMAGE=$(cat .imageID)
  echo "Removing image  $IMAGE..."
  docker image rm -f $IMAGE
  rm -f .imageID
  if [ $? -eq 0 ] 
  then 
    echo "Image removed succesfully. All done!"
  else 
    echo "Couldn't remove image."
  fi 
fi 
exit 0